<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import { knowledgeTerms } from '../data/demo'
const route=useRoute(); const query=ref(String(route.query.term||'')); const category=ref('')
const filtered=computed(()=>knowledgeTerms.filter(i=>(!query.value||i.term.includes(query.value)||i.definition.includes(query.value))&&(!category.value||i.category===category.value)))
const dynasties=[['唐','结构舒展，出檐深远，构件尺度雄健'],['五代','承唐启宋，早期木构实例稀少而关键'],['辽','保留早期营造特征，斗拱与梁架富于变化'],['宋','营造制度成熟，建筑与造像审美并进'],['金','继承辽宋并发展出鲜明地域特点'],['元','壁画、彩塑与木构呈现多元交流'],['明','寺观修建活跃，彩塑与悬塑形成高峰']]
</script>
<template><div class="dictionary-page"><header><span>KNOWLEDGE DICTIONARY</span><h1>古建知识字典</h1><p>先认识构件与造像语言，再回到游戏和现场看细节。</p><div><input v-model="query" placeholder="搜索术语"><select v-model="category"><option value="">全部分类</option><option>木构</option><option>构件</option><option>彩塑</option><option>造像</option></select></div></header><main><section><div class="term-grid"><article v-for="item in filtered" :key="item.term"><small>{{ item.category }}</small><h2>{{ item.term }}</h2><p>{{ item.definition }}</p><footer>相关：{{ item.related.join(' · ') }}</footer></article></div></section><section class="timeline"><div class="section-title"><span>DYNASTY TIMELINE</span><h2>山西古建朝代速查</h2></div><div><article v-for="item in dynasties" :key="item[0]"><b>{{ item[0] }}</b><p>{{ item[1] }}</p></article></div></section></main></div></template>
<style scoped>.dictionary-page{height:100%;overflow-y:auto;background:#e9e1d4;color:#29241d}.dictionary-page>header{padding:70px max(30px,calc((100% - 1080px)/2));background:#1a1712;color:#e9e0d1}.dictionary-page>header>span,.section-title span{color:#b79256;font-size:10px;letter-spacing:3px}.dictionary-page h1{font:42px Georgia,'Songti SC',serif;letter-spacing:0;margin:10px 0}.dictionary-page header p{color:#9e9588}.dictionary-page header div{display:flex;gap:8px;margin-top:28px}.dictionary-page input,.dictionary-page select{height:40px;background:#26221b;border:1px solid #41392e;color:#ddd2c1;padding:0 12px}.dictionary-page input{width:280px}.dictionary-page main{max-width:1080px;margin:auto;padding:55px 30px 80px}.term-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.term-grid article{background:#f3ede3;border:1px solid #d1c5b4;padding:24px;min-height:210px}.term-grid small{color:#9a7844}.term-grid h2{font:29px Georgia,'Songti SC',serif;margin:11px 0}.term-grid p{color:#675e52;line-height:1.8;font-size:12px}.term-grid footer{margin-top:18px;padding-top:11px;border-top:1px solid #ddd2c2;color:#9b8e7c;font-size:10px}.timeline{margin-top:70px}.section-title h2{font:30px Georgia,'Songti SC',serif;margin:8px 0 24px}.timeline>div:last-child{display:grid;grid-template-columns:repeat(7,1fr);border-top:1px solid #ad9267}.timeline article{padding:20px 13px;border-right:1px solid #d1c5b4}.timeline b{font:25px Georgia,'Songti SC',serif;color:#8d6b36}.timeline p{font-size:10px;line-height:1.7;color:#73695d;margin-top:12px}@media(max-width:760px){.dictionary-page>header{padding:48px 20px}.dictionary-page header div{display:grid}.dictionary-page input{width:100%}.dictionary-page main{padding:40px 20px}.term-grid{grid-template-columns:1fr}.timeline>div:last-child{grid-template-columns:1fr}.timeline article{display:grid;grid-template-columns:50px 1fr}.timeline p{margin-top:0}}</style>
