<script setup lang="ts">
import { ref } from 'vue'
import OLViewer from '../components/openlayers/OLViewer.vue'
import { demoLocations, themeRoutes } from '../data/demo'
const selected=ref(themeRoutes[0]); const selectedId=ref<number|null>(selected.value.locationIds[0])
function choose(route:typeof themeRoutes[number]){selected.value=route;selectedId.value=route.locationIds[0]}
</script>
<template><div class="routes-page"><header><span>THEME ROUTES</span><h1>沿着一条线，读懂一种古建语言</h1><p>路线用于行前内容组织与地图示意，不提供实时导航和耗时预测。</p></header><main><aside><button v-for="item in themeRoutes" :key="item.id" :class="{active:selected.id===item.id}" @click="choose(item)"><small>{{ item.theme }}</small><strong>{{ item.name }}</strong><span>{{ item.days }} 天 · {{ item.locationIds.length }} 处古建</span><p>{{ item.description }}</p></button></aside><section><div class="map"><OLViewer :locations="demoLocations.filter(i=>selected.locationIds.includes(i.id))" :selected-location-id="selectedId" @select-location="selectedId=$event" @view-detail="selectedId=$event"/></div><div class="route-plan"><h2>{{ selected.name }}</h2><article v-for="(id,index) in selected.locationIds" :key="id"><b>DAY {{ Math.min(index+1,selected.days) }}</b><div><strong>{{ demoLocations.find(i=>i.id===id)?.name }}</strong><p>{{ demoLocations.find(i=>i.id===id)?.highlight }} · 查看相关图鉴条目与现场信息</p></div></article></div></section></main></div></template>
<style scoped>.routes-page{height:100%;overflow-y:auto;background:#15130f;color:#e9e1d4}.routes-page>header{max-width:1120px;margin:auto;padding:60px 35px 34px}.routes-page>header span{color:#b89255;font-size:10px;letter-spacing:3px}.routes-page h1{font:38px Georgia,'Songti SC',serif;letter-spacing:0;margin:10px 0}.routes-page>header p{color:#968d80}.routes-page main{max-width:1120px;margin:auto;padding:0 35px 80px;display:grid;grid-template-columns:300px 1fr;gap:16px}.routes-page aside{display:grid;align-content:start;gap:9px}.routes-page aside button{text-align:left;background:#1f1c16;border:1px solid #373128;color:#aaa094;padding:19px;cursor:pointer}.routes-page aside button.active{border-color:#9c7b45;background:#282116}.routes-page aside small{color:#b08d54}.routes-page aside strong{display:block;color:#eee5d5;font:21px Georgia,'Songti SC',serif;margin:8px 0}.routes-page aside span{font-size:10px}.routes-page aside p{font-size:11px;line-height:1.7;margin-top:12px}.routes-page main>section{min-width:0}.map{height:390px;border:1px solid #373128}.route-plan{padding:24px;background:#e8e0d3;color:#2b261f}.route-plan h2{font:27px Georgia,'Songti SC',serif;margin-bottom:15px}.route-plan article{display:grid;grid-template-columns:70px 1fr;gap:13px;padding:14px 0;border-top:1px solid #cfc2af}.route-plan article>b{color:#9a743d;font-size:10px}.route-plan article p{font-size:10px;color:#776d60;margin-top:4px}@media(max-width:760px){.routes-page>header{padding:45px 20px 25px}.routes-page h1{font-size:30px}.routes-page main{grid-template-columns:1fr;padding:0 20px 60px}.map{height:310px}}</style>
